### ISSUE TITLE
Get error with builiding

### ISSUE THREAD

**Issue by JLDDER** [acsbendi/Build-SFML-For-Android-On-Windows#2]
Thank you for providing such a convenient code.
But I got in trouble with building in src\SFML\Network\Socket.cpp
**get error : delegating constructors are permitted only in C++11**
`Socket::Socket(Socket &&rvalue) : Socket(rvalue.m_type)`
and 
**get error : no type named 'move' in namespace 'std'**
`Socket tmp(std::move(rvalue));`
it seems that c++ version is not fitable?
but I have already install lastest version.
Could you have ideal with this? Thanks.

**Comment by acsbendi** [comment]
You're welcome!
Yes, I had a few changes in my SFML-fork that were not compatible with pre-C++11 compilers.
Reverted these now, if you delete your local SFML repo and run the script again, it will work.
